"use client"
import { PageHeading } from "@/components/page-heading"
import { WellnessPhoto } from "@/components/wellness-photo"
import {useEffect,useState} from "react"
import Link from "next/link"
import {ProfileReadinessCard} from "@/components/profile-readiness"
import {profileReadiness} from "@/lib/profile-readiness"
import {Localize,useLanguage} from "@/lib/i18n/provider"
import {getUser,saveMyPlan,type PublicUser} from "@/app/actions"
import {BodyDataEditor} from "@/components/body-data"
import {GoalEditor} from "@/components/goal-editor"
import {SlotChoices} from "@/components/planning-preferences"
import {readPreferences,healthOptions,type Preferences} from "@/lib/preferences"
import {parseStringList} from "@/lib/dietary"
import {displayValue} from "@/lib/display"
import {Button} from "@/components/ui/button"
import {editableNumber} from "@/lib/editable-number"
export default function MyPlan(){
 const [welcome,setWelcome]=useState(false)
 const [user,setUser]=useState<PublicUser|null>(null),[error,setError]=useState("")
 useEffect(()=>{setWelcome(new URLSearchParams(window.location.search).has("welcome"));getUser().then(setUser).catch(()=>setError("Kunde inte ladda profilen. Försök igen."))},[])
 return <Localize><div className="app-page settings-page max-w-4xl mx-auto space-y-8">
  <div className="overflow-hidden rounded-[2rem] border border-[#e3e6d9] bg-white">
    <div className="h-48 sm:h-72 relative">
      <WellnessPhoto src="/images/lifestyle/my-plan.png" className="w-full h-full object-cover object-[50%_85%]" />
    </div>
    <div className="p-6 sm:p-8 lg:p-10 border-t">
      <PageHeading section="plan" />
      <p className="text-lg text-muted-foreground mt-2">Här anpassar du planen. Registrera dagens resultat under Framsteg.</p>
    </div>
  </div>
  {welcome&&user&&profileReadiness(user).ready&&<section className="rounded border bg-secondary p-4 space-y-3"><h2 className="font-semibold">Din grundplan är klar. Vill du göra den ännu mer personlig?</h2><Link className="underline" href="/dashboard">Börja med min grundplan</Link></section>}
  <nav className="settings-jumps flex flex-wrap gap-2 text-sm">{[["body","Kropp och grunddata"],["food","Mat"],["health","Hälsoanpassning"],["training","Träning"],["daily","Vardag"]].map(([id,label])=><a key={id} href={`#${id}`}>{label}</a>)}</nav>{user?<><ProfileReadinessCard user={user}/><BodyDataEditor user={user} onSaved={setUser}/><GoalEditor user={user} onSaved={setUser}/><PlanForm initial={user} onSaved={setUser}/></>:<p role="status">{error||"Laddar din profil…"}</p>}</div></Localize>
}
function PlanForm({initial,onSaved}:{initial:PublicUser;onSaved:(user:PublicUser)=>void}){
 const {language}=useLanguage(),en=language==="en"
 const [p,setP]=useState(readPreferences(initial.preferences)),[rules,setRules]=useState(parseStringList(initial.dietRestrictions).filter(v=>!v.startsWith("allergy:"))),[allergies,setAllergies]=useState(parseStringList(initial.dietRestrictions).filter(v=>v.startsWith("allergy:")).map(v=>v.slice(8)).join(", ")),[dislikes,setDislikes]=useState(parseStringList(initial.dislikedFoods).join(", ")),[life,setLife]=useState(parseStringList(initial.lifestyle)),[location,setLocation]=useState(readPreferences(initial.preferences).planningConfirmed?initial.trainingLocation:""),[level,setLevel]=useState(readPreferences(initial.preferences).planningConfirmed?initial.trainingLevel:""),[activity,setActivity]=useState(readPreferences(initial.preferences).planningConfirmed?initial.activityLevel||"":""),[saving,setSaving]=useState(false),[message,setMessage]=useState("")
 const select=(label:string,value:string,options:Record<string,string>,change:(v:string)=>void)=><label className="block text-sm">{label}<select className="w-full border rounded p-2" value={value} onChange={e=>change(e.target.value)}><option value="">{en?"Choose…":"Välj…"}</option>{Object.entries(options).map(([key,text])=><option key={key} value={key}>{text}</option>)}</select></label>
 const number=(label:string,key:"cookingMinutes"|"workoutMinutes"|"trainingDays"|"dailySteps",min:number,max:number)=><label className="block text-sm">{label}<input className="w-full border rounded p-2" type="number" step={1} min={min} max={max} required value={Number.isFinite(p[key])?p[key]:""} onChange={e=>setP({...p,[key]:editableNumber(e.target.value)})}/></label>
 const split=(value:string)=>value.split(",").map(v=>v.trim()).filter(Boolean)
 return <Localize><form className="space-y-6" onSubmit={async e=>{e.preventDefault();setSaving(true);setMessage("");try{if(!p.planningConfirmed)throw new Error("Confirm choices");await saveMyPlan({dietRestrictions:[...rules,...split(allergies).map(v=>`allergy:${v.toLowerCase()}`)],dislikedFoods:split(dislikes),lifestyle:life,trainingLocation:location,trainingLevel:level,activityLevel:activity,preferences:{...p,trackedMeasurements:readPreferences(initial.preferences).trackedMeasurements}});const updated=await getUser();if(updated)onSaved(updated);setMessage("Dina val är sparade.")}catch{setMessage("Kunde inte spara. Kontrollera dina val.")}finally{setSaving(false)}}}>
 <fieldset disabled={saving} className="space-y-6"><p data-localize="off" className="rounded-xl bg-amber-50 p-4 text-sm">{en?"Review these saved values and starting suggestions. They become confirmed planning inputs only when you approve and save below.":"Granska sparade värden och startförslag. De blir bekräftade planeringsuppgifter först när du godkänner och sparar nedan."}</p>
 <section id="food" className="wellness-panel p-5 sm:p-6 space-y-4 scroll-mt-4"><h2 className="font-semibold text-xl">Mat</h2><div className="flex flex-wrap gap-4">{["vegetarian","vegan","lactose-free","gluten-free","halal","kosher"].map(rule=><label key={rule} className="flex gap-2 items-center min-h-11"><input type="checkbox" checked={rules.includes(rule)} onChange={e=>setRules(e.target.checked?[...rules,rule]:rules.filter(v=>v!==rule))}/>{displayValue(rule)}</label>)}</div><label className="block text-sm">Allergier (komma mellan, t.ex. nötter, mjölk, ägg, soja)<input className="w-full border rounded p-2" maxLength={500} value={allergies} onChange={e=>setAllergies(e.target.value)}/></label><p className="text-sm">Laktosfri kost är inte samma sak som mjölkallergi. Kontrollera alltid produktmärkningen.</p><label className="block text-sm">Mat du gillar<input className="w-full border rounded p-2" maxLength={500} value={p.likedFoods} onChange={e=>setP({...p,likedFoods:e.target.value})}/></label><label className="block text-sm">Mat du ogillar (separera med komma)<input className="w-full border rounded p-2" maxLength={500} value={dislikes} onChange={e=>setDislikes(e.target.value)}/></label>{select("Matbudget",p.budget,{low:"Låg",normal:"Normal",high:"Hög"},budget=>setP({...p,budget}))}{number("Tid för matlagning (min)","cookingMinutes",5,180)}<fieldset><legend>Måltider för nya veckor</legend><SlotChoices value={p.mealSlots} onChange={mealSlots=>setP({...p,mealSlots})}/><p className="text-sm">Befintliga veckor ändras på Veckoplan. En bortvald måltid betyder att du planerar den själv, inte att du ska hoppa över mat.</p></fieldset></section>
 <section id="health" className="wellness-panel p-5 sm:p-6 space-y-3"><h2 className="font-semibold text-xl">Hälsoanpassning</h2>{select("Hälsoanpassning (valfritt)",p.health,healthOptions,health=>setP({...p,health:health as Preferences["health"]}))}<p className="text-sm">Kost- och planeringsstöd, inte behandling eller ersättning för vårdens råd. Vi ändrar aldrig medicin eller insulindos. Allergier och kostkrav går alltid först.</p></section>
 <section id="training" className="wellness-panel p-5 sm:p-6 space-y-3"><h2 className="font-semibold text-xl">Träning</h2>{select("Träningsnivå",level,{beginner:"Nybörjare",intermediate:"Medelnivå",advanced:"Avancerad"},setLevel)}{select("Träningsplats",location,{home:"Hemma",gym:"Gym",both:"Hemma och gym"},setLocation)}<label className="block text-sm">Utrustning hemma<input className="w-full border rounded p-2" maxLength={500} value={p.equipment} onChange={e=>setP({...p,equipment:e.target.value})}/></label><p className="text-sm">Skriv utrustning du har, separerad med komma, till exempel kroppsvikt, hantlar, bänk. Valet gäller hemmapass. Gym innebär vanliga gymmaskiner och fria vikter. Kroppsviktspass kan använda golv och vägg.</p>{number("Realistiska träningsdagar/vecka","trainingDays",0,5)}{number("Tid per pass (min)","workoutMinutes",10,120)}</section>
 <section id="daily" className="wellness-panel p-5 sm:p-6 space-y-3"><h2 className="font-semibold text-xl">Vardag</h2>{select("Aktivitetsnivå",activity,{sedentary:"Mestadels stillasittande",light:"Lätt aktiv",moderate:"Måttligt aktiv",active:"Aktiv",very_active:"Mycket aktiv"},setActivity)}{number("Ungefärliga steg per dag","dailySteps",0,50000)}{select("Arbetstider",p.workSchedule,{dagtid:"Dagtid",kvall:"Kvällstid",natt:"Natt",skift:"Skift",oregelbundet:"Oregelbundna tider"},workSchedule=>setP({...p,workSchedule}))}<div className="flex flex-wrap gap-4">{["office-worker","active-job","travels","family","no-microwave","no-fridge","meal-prep"].map(v=><label key={v} className="flex gap-2 items-center min-h-11"><input type="checkbox" checked={life.includes(v)} onChange={e=>setLife(e.target.checked?[...life,v]:life.filter(k=>k!==v))}/>{displayValue(v)}</label>)}</div></section>
 <p className="text-sm">Sparade ändringar uppdaterar kommande måltider och träning. Dagarnas måltidsval och tidigare loggar behålls.</p><label data-localize="off" className="flex min-h-12 gap-3 items-center"><input type="checkbox" checked={p.planningConfirmed===true} onChange={e=>setP({...p,planningConfirmed:e.target.checked})}/>{en?"I have reviewed my activity, training and daily-life choices, including the suggested step goal (typical steps + 1000, limited to 2000–12000).":"Jag har granskat aktivitet, träning och vardagsval, inklusive föreslaget stegmål (vanliga steg + 1000, begränsat till 2000–12000)."}</label><Button type="submit" disabled={saving||!p.planningConfirmed}>Spara min plan</Button></fieldset><p role="status">{message}</p></form></Localize>
}
