"use client"
import { WelcomeCollage } from "@/components/welcome-collage"
import Link from "next/link"
import { Leaf } from "lucide-react"
import { useState } from "react"
import { useRouter } from "next/navigation"
import { signIn } from "next-auth/react"
import { useLanguage } from "@/lib/i18n/provider"
import { BirthInputs } from "@/components/body-data"
import { StartingChoices } from "@/components/starting-choices"
import { Button } from "@/components/ui/button"
import { defaultPreferences, type Preferences } from "@/lib/preferences"
import { primaryGoals,goalLabels,type PrimaryGoal } from "@/lib/nutrition"
import { onboardingErrors } from "@/lib/onboarding-validation"
import { timeframeOptions } from "@/lib/goal-safety"
import { submitOnboarding } from "@/app/actions"

export default function OnboardingPage(){
 const {language,ready}=useLanguage(),en=language==="en",router=useRouter(),t=(sv:string,english:string)=>en?english:sv
 const [step,setStep]=useState(1),[busy,setBusy]=useState(false),[errors,setErrors]=useState<Record<string,string>>({}),[error,setError]=useState("")
 const [data,setData]=useState({name:"",email:"",password:"",currentWeight:"",height:"",targetWeight:"",timeframeWeeks:"",activityLevel:"",trainingLevel:"",trainingLocation:"",dietRestrictions:[] as string[],allergies:"",mode:"simple",preferences:{...defaultPreferences,planningConfirmed:false} as Preferences})
 const goal=data.preferences.primaryGoal,maintaining=goal==="maintain"||goal==="retain-muscle"
 const validate=(which:number)=>{const next=onboardingErrors(data,which,en);setErrors(next);return !Object.keys(next).length}
 const next=()=>{if(validate(step))setStep(step+1)}
 const field=(key:"name"|"email"|"password"|"currentWeight"|"height"|"targetWeight",label:string,type="text")=><label className="block text-sm font-medium">{label}<input aria-invalid={!!errors[key]} aria-describedby={errors[key]?key+"-error":undefined} className={"mt-1 w-full rounded-xl border p-3 "+(errors[key]?"border-red-600":"border-gray-300")} type={type} step={type==="number"?"any":undefined} value={data[key]} onChange={e=>setData({...data,[key]:e.target.value})}/>{errors[key]&&<span id={key+"-error"} className="mt-1 block text-red-700">{errors[key]}</span>}</label>
 const select=(key:"activityLevel"|"trainingLevel"|"trainingLocation",label:string,values:string[],labels:string[])=><label className="block text-sm font-medium">{label}<select aria-invalid={!!errors[key]} className="mt-1 w-full rounded-xl border p-3" value={data[key]} onChange={e=>setData({...data,[key]:e.target.value})}><option value="">{t("Välj…","Choose…")}</option>{values.map((v,i)=><option key={v} value={v}>{labels[i]}</option>)}</select>{errors[key]&&<span className="block text-red-700">{errors[key]}</span>}</label>
 const finish=async()=>{
  for(const which of [1,3,4])if(!validate(which)){setStep(which);return}
  setBusy(true);setError("")
  try{const result=await submitOnboarding({...data,preferences:{...data.preferences,language},dietRestrictions:[...data.dietRestrictions,...data.allergies.split(",").map(v=>v.trim().toLowerCase()).filter(Boolean).map(v=>"allergy:"+v)]});if(!result.success){setError(result.error);return}const login=await signIn("credentials",{redirect:false,email:data.email,password:data.password});router.push(login?.error?"/login?created=1":"/home")}catch{setError(t("Kunde inte skapa kontot. Försök igen.","Could not create your account. Please try again."))}finally{setBusy(false)}
 }
 const StepHeading = step === 1 ? "h2" : "h1"
 return <main className="wellness-app min-h-screen bg-background px-4 py-8"><header className="mx-auto mb-8 flex max-w-5xl items-center justify-between gap-4"><Link href="/" className="inline-flex items-center gap-2 font-serif text-xl text-primary"><Leaf className="h-6 w-6" />Livskraft</Link><Link href="/login" className="inline-flex min-h-11 items-center text-sm font-medium text-primary">{t("Logga in","Log in")}</Link></header>{step===1&&<section className="onboarding-welcome mx-auto mb-8 grid max-w-5xl items-center gap-6 rounded-[2rem] border bg-[#f2f5e9] p-5 sm:p-8 lg:grid-cols-2"><div><p className="wellness-eyebrow">{t("VÄLKOMMEN TILL LIVSKRAFT","WELCOME TO LIVSKRAFT")}</p><h1 className="mt-3 text-3xl font-semibold">{t("En plan för hela din vardag.","A plan for your everyday life.")}</h1><p className="mt-4 text-sm leading-relaxed text-muted-foreground">{t("Mat, rörelse och återhämtning. Vi börjar med dig och det som passar ditt liv.","Food, movement and recovery. We start with you and what fits your life.")}</p><Button asChild className="mt-5"><a href="#onboarding-fields">{t("Börja med mig","Start with me")}</a></Button></div><WelcomeCollage /></section>}<div id="onboarding-fields" className="mx-auto max-w-xl rounded-3xl border bg-white p-5 shadow-sm sm:p-8"><p className="font-semibold text-primary">Livskraft</p><p className="mt-4 text-sm text-muted-foreground">{t("Steg","Step")} {step} {t("av","of")} 4</p><StepHeading className="mt-2 text-2xl font-semibold">{[t("Börja med dig","Start with you"),t("Mat som passar dig","Food that fits you"),t("Din vardag och träning","Your activity and training"),t("Granska din start","Review your start")][step-1]}</StepHeading><p className="mt-2 mb-6 text-sm text-muted-foreground">{t("Din plan ska passa ditt liv. Frivilliga uppgifter är märkta.","Your plan should fit your life. Optional fields are labelled.")}</p>
 {step===1&&<div className="space-y-4">{field("name",t("Ditt namn","Your name"))}{field("email",t("E-post","Email"),"email")}{field("password",t("Lösenord (10–256 tecken)","Password (10–256 characters)"),"password")}<div className="grid gap-4 sm:grid-cols-2">{field("currentWeight",t("Nuvarande vikt (kg)","Current weight (kg)"),"number")}{field("height",t("Längd (cm)","Height (cm)"),"number")}</div>
 <label className="block text-sm font-medium">{t("Huvudmål","Primary goal")}<select aria-invalid={!!errors.goal} className="mt-1 w-full rounded-xl border p-3" value={goal??""} onChange={e=>{setErrors({});setData({...data,targetWeight:"",timeframeWeeks:"",preferences:{...data.preferences,primaryGoal:(e.target.value||undefined) as PrimaryGoal|undefined}})}}><option value="">{t("Välj ditt mål…","Choose your goal…")}</option>{primaryGoals.map(g=><option key={g} value={g}>{goalLabels[language][g]}</option>)}</select>{errors.goal&&<span className="block text-red-700">{errors.goal}</span>}</label>
 {maintaining&&<p className="rounded-xl bg-emerald-50 p-3 text-sm">{goal==="retain-muscle"?t("Vi fokuserar på stabil vikt, protein, styrketräning och återhämtning. Ingen tidsram för viktnedgång behövs.","We focus on stable weight, protein, resistance training and recovery. No weight-loss timeframe is needed."):t("Vi fokuserar på viktstabilitet. Du behöver inte ange en annan målvikt eller tidsram.","We focus on weight stability. No different target weight or timeframe is needed.")}</p>}
 {(goal==="lose"||goal==="build-muscle")&&<div className="space-y-3">{goal==="build-muscle"&&<p className="text-sm">{t("Bygg styrka i lugn takt. Ett viktökningsmål är frivilligt; anger du ett mål behövs även en tidsram.","Build strength gradually. A weight-gain target is optional; if you enter one, include a timeframe.")}</p>}{field("targetWeight",goal==="build-muscle"?t("Viktmål för muskelbygge (frivilligt, kg)","Muscle-building weight target (optional, kg)"):t("Målvikt (kg)","Target weight (kg)"),"number")}<label className="block text-sm">{t("Tidsram","Timeframe")}<select className="mt-1 w-full rounded-xl border p-3" value={data.timeframeWeeks} onChange={e=>setData({...data,timeframeWeeks:e.target.value})}><option value="">{t("Välj tidsram…","Choose timeframe…")}</option>{timeframeOptions.map(o=><option key={o.weeks} value={o.weeks}>{en?o.weeks+(o.weeks===1?" week":" weeks"):o.label}</option>)}</select></label></div>}
 <BirthInputs value={data.preferences} onChange={body=>setData({...data,preferences:{...data.preferences,...body}})}/>{errors.birthYear&&<p className="text-red-700">{errors.birthYear}</p>}</div>}
 {step===2&&<div className="space-y-4"><p className="text-sm">{t("Frivilliga kostval. Ange allergier separat och kontrollera produktmärkningen.","Optional food preferences. Enter allergies separately and check product labels.")}</p>{["vegetarian","vegan","lactose-free","gluten-free","halal","kosher"].map((v,i)=><label key={v} className="flex min-h-12 items-center gap-3"><input type="checkbox" checked={data.dietRestrictions.includes(v)} onChange={e=>setData({...data,dietRestrictions:e.target.checked?[...data.dietRestrictions,v]:data.dietRestrictions.filter(x=>x!==v)})}/>{(en?["Vegetarian","Vegan","Lactose-free","Gluten-free","Halal","Kosher"]:["Vegetarisk","Vegansk","Laktosfri","Glutenfri","Halal","Kosher"])[i]}</label>)}<label className="block text-sm">{t("Allergier, separera med komma (frivilligt)","Allergies, comma-separated (optional)")}<input maxLength={500} className="mt-1 w-full rounded-xl border p-3" value={data.allergies} onChange={e=>setData({...data,allergies:e.target.value})}/></label></div>}
 {step===3&&<div className="space-y-4">{select("activityLevel",t("Aktivitetsnivå","Activity level"),["sedentary","light","moderate","active","very_active"],en?["Mostly seated","Lightly active","Moderately active","Active","Very active"]:["Mestadels stillasittande","Lätt aktiv","Måttligt aktiv","Aktiv","Mycket aktiv"])}{select("trainingLevel",t("Träningsnivå","Training level"),["beginner","intermediate","advanced"],en?["Beginner","Intermediate","Advanced"]:["Nybörjare","Medelnivå","Avancerad"])}{select("trainingLocation",t("Var vill du träna?","Where would you like to train?"),["home","gym","both"],en?["Home","Gym","Home and gym"]:["Hemma","Gym","Hemma och gym"])}</div>}
 {step===4&&<div className="space-y-4"><StartingChoices value={data.preferences} onChange={preferences=>setData({...data,preferences})}/>{errors.choices&&<p className="text-red-700">{errors.choices}</p>}{errors.confirmation&&<p className="text-red-700">{errors.confirmation}</p>}<label className="block text-sm">{t("Visningsläge","Display mode")}<select className="w-full rounded-xl border p-3" value={data.mode} onChange={e=>setData({...data,mode:e.target.value})}><option value="simple">{t("Enkelt","Simple")}</option><option value="advanced">{t("Avancerat","Advanced")}</option></select></label></div>}
 {Object.keys(errors).length>0&&<p role="alert" className="mt-4 text-sm text-red-700">{t("Kontrollera de markerade fälten innan du fortsätter.","Check the marked fields before continuing.")}</p>}{error&&<p role="alert" className="mt-4 text-red-700">{error}</p>}<div className="mt-6 flex gap-3">{step>1&&<Button variant="outline" disabled={busy} onClick={()=>{setErrors({});setStep(step-1)}}>{t("Tillbaka","Back")}</Button>}<Button className="min-h-12 flex-1" disabled={busy||!ready} onClick={step===4?finish:next}>{busy?t("Skapar konto…","Creating account…"):step===4?t("Välkommen till Livskraft","Enter Livskraft"):t("Nästa","Next")}</Button></div></div></main>
}
