export const recipeInstructions: Record<string,string[]> = {
  "Krämig Havregröt med Bär": ["Koka upp havregryn och vatten i en liten kastrull. Sänk till låg värme och sjud 3–5 minuter under omrörning.","Värm bären separat enligt förpackningens anvisningar och rör ner dem. Späd gröten med lite av den angivna mjölken om den blir för tjock.","Servera med linfrön och resten av den laktosfria mjölken."],
  "Tofu-wok med ris": ["Koka riset enligt förpackningen. Låt tofun rinna av, torka den lätt och skär i tärningar.","Dela broccoli och paprika i små bitar. Hacka vitlöken. Hetta upp en nonstickpanna på medelhög värme och stek tofun 5–7 minuter; vänd så att flera sidor får färg.","Lägg i grönsakerna och ett par matskedar vatten. Tillaga 4–5 minuter under omrörning, tills broccolin mjuknar men har tuggmotstånd.","Sänk värmen, tillsätt vitlök och glutenfri soja och rör om 1 minut. Servera med riset."],
  "Kikärtsgryta med tomat": ["Sätt riset på kokning enligt förpackningen. Skölj kikärtorna och hacka löken.","Mjukna löken i en kastrull med lite vatten på medelvärme i 3–4 minuter; tillsätt mer vatten om det behövs.","Rör ner spiskummin, kikärtor och krossade tomater. Låt sjuda på låg värme i cirka 15 minuter och rör om ibland.","Smaka av och servera med riset. Anpassa mängden efter hunger."],
  "Snabb Kycklingwok med Nudlar": ["Koka upp vatten till nudlarna. Dela broccolin i små buketter och hacka vitlöken. Använd separat skärbräda för rå kyckling.","Strimla kycklingen. Hetta upp en nonstickpanna på medelhög värme och stek cirka 6–8 minuter under omrörning; kontrollera att kycklingen blir helt genomstekt.","Koka nudlarna enligt förpackningen och låt broccolin koka med de sista 2–3 minuterna. Häll av och spara lite kokvatten.","Sänk värmen i pannan. Tillsätt vitlök och soja, vänd ner nudlar och broccoli och värm 1–2 minuter. Späd med lite kokvatten vid behov."],
  "Lax med rostad potatis": ["Sätt ugnen på 200 °C. Skär potatisen i små klyftor, blanda med rapsoljan och lägg i en ugnsform.","Rosta potatisen cirka 15 minuter. Lägg laxen bredvid och fortsätt tillaga omkring 12–15 minuter, tills potatisen är mjuk och fisken är genomlagad; tiden beror på bitarnas storlek.","Dela broccolin i buketter och koka eller ånga 4–5 minuter. Servera med lax, potatis och citron."],
  "Röd lins-soppa": ["Skölj linserna. Hacka löken och skär morötterna i små bitar.","Mjukna lök och morot med lite vatten i en kastrull på medelvärme i 4–5 minuter.","Tillsätt linser, gurkmeja och den angivna mängden färdigblandad grönsaksbuljong. Om du använder koncentrat eller tärning, följ förpackningens dosering och kontrollera innehållet mot din kostprofil.","Koka upp, sänk värmen och sjud 15–20 minuter tills linser och morötter är mjuka. Rör om ibland. Mixa försiktigt om du vill ha slätare konsistens."],
  "Spenatomelett med tomat": ["Skölj spenat och tomat. Skär tomaten i små bitar och vispa äggen lätt med svartpeppar.","Värm rapsoljan i en liten stekpanna på medelvärme. Låt spenaten mjukna i ungefär 1 minut.","Häll i äggen och fördela tomaten ovanpå. Sänk värmen och tillaga 4–5 minuter, gärna under lock, tills äggsmeten stelnat."],
  "Quinoasallad med gurka": ["Skölj quinoan noggrant i en sil. Koka enligt förpackningen, vanligtvis cirka 15 minuter, och låt ånga av.","Skölj gurka och tomater. Skär gurkan i bitar och halvera tomaterna.","Blanda quinoa, grönsaker, olivolja och pressad citron. Servera ljummen eller kyl snabbt och förvara i kylskåp till nästa måltid."],
  "Jordnötstofu med ris": ["Koka riset enligt förpackningen. Låt tofun rinna av och skär i tärningar.","Stek tofun i en nonstickpanna på medelhög värme i cirka 6 minuter; vänd under tiden.","Rör ut jordnötssmöret med soja och lite varmt vatten till en sås. Sänk värmen och blanda med tofun i 1–2 minuter. Servera med ris."],
  "Halloumisallad": ["Skölj sallad, tomat och gurka. Skär grönsakerna och lägg på en tallrik.","Skiva halloumin och stek i nonstickpanna på medelhög värme cirka 2 minuter per sida, tills den får färg.","Lägg osten på grönsakerna, ringla över olivolja och servera direkt."],
  "Bönchili med ris": ["Koka riset enligt förpackningen. Skölj bönorna och tärna paprikan.","Mjukna paprikan med lite vatten i en kastrull på medelvärme i 3–4 minuter.","Tillsätt bönor, krossade tomater och chili efter smak. Sjud på låg värme i cirka 15 minuter; rör om då och då och späd med vatten vid behov.","Smaka av och servera med riset."],
}
