"use client"
import { useEffect, useState } from "react"
import { bodyLabels, type BodyData } from "@/lib/body-data"
import Link from "next/link"
import { readPreferences, measurementLabels, type MeasurementKey } from "@/lib/preferences"
import { useLanguage } from "@/lib/i18n/provider"
import { saveBodyData, getBodyMeasurements } from "@/app/nutrition-actions"
import { getUser, type PublicUser } from "@/app/actions"
import { Button } from "./ui/button"
export function BirthInputs({value,onChange}:{value:BodyData;onChange:(value:BodyData)=>void}) {
  const {language}=useLanguage(), labels=bodyLabels[language]
  return <div className="space-y-3" data-localize="off"><p className="text-sm">{language==="en"?"Used only to improve the energy estimate.":"Används endast för att förbättra energiuppskattningen."}</p><details><summary className="cursor-pointer text-sm underline">{language==="en"?"Why do we ask?":"Varför frågar vi?"}</summary><p className="mt-2 text-sm">{labels.explanation}</p></details><div className="grid gap-3 sm:grid-cols-2"><label>{labels.year}<input className="w-full border rounded p-2" type="number" min={new Date().getFullYear()-100} max={new Date().getFullYear()-18} value={value.birthYear??""} onChange={e=>onChange({...value,birthYear:e.target.value?Number(e.target.value):undefined})}/></label><label>{labels.sex}<select className="w-full border rounded p-2" value={value.sexForEnergy??"undisclosed"} onChange={e=>onChange({...value,sexForEnergy:e.target.value as BodyData["sexForEnergy"]})}>{(["undisclosed","male","female"] as const).map(key=><option key={key} value={key}>{labels[key]}</option>)}</select></label></div></div>
}
export function BodyDataEditor({user,onSaved}:{user:PublicUser;onSaved:(user:PublicUser)=>void}) {
  const {language}=useLanguage(), labels=bodyLabels[language], en=language==="en"
  const [body,setBody]=useState<BodyData>(readPreferences(user.preferences)),[height,setHeight]=useState(String(user.height??"")),[weight,setWeight]=useState(String(user.currentWeight??""))
  useEffect(()=>{setBody(readPreferences(user.preferences));setHeight(String(user.height??""));setWeight(String(user.currentWeight??""))},[user.preferences,user.height,user.currentWeight])
  const [busy,setBusy]=useState(false),[message,setMessage]=useState("")
  const [tracked,setTracked]=useState(readPreferences(user.preferences).trackedMeasurements),[waist,setWaist]=useState(String(user.waist??"")),[values,setValues]=useState<Partial<Record<MeasurementKey,string>>>({}),[loaded,setLoaded]=useState(false)
  useEffect(()=>{let active=true;getBodyMeasurements().then(saved=>{if(active){setValues(Object.fromEntries(Object.entries(saved).map(([key,value])=>[key,String(value)])));setLoaded(true)}}).catch(()=>{if(active)setMessage(en?"Could not load measurements. Reload before saving.":"Kunde inte läsa måtten. Ladda om före sparande.")});return()=>{active=false}},[user.id,en])
  const names={hip:en?"Hip":"Höft",chest:en?"Chest":"Bröst",thigh:en?"Thigh":"Lår",arm:en?"Upper arm":"Överarm",neck:en?"Neck":"Hals",calf:en?"Calf":"Vad"}
  return <form id="body" className="wellness-panel p-5 sm:p-6 space-y-4" data-localize="off" onSubmit={async e=>{e.preventDefault();if(!loaded||busy)return;setBusy(true);setMessage("");try{await saveBodyData({birthYear:body.birthYear,sexForEnergy:body.sexForEnergy,height:height?Number(height):null,currentWeight:weight?Number(weight):null,waist:waist?Number(waist):undefined,trackedMeasurements:tracked,values:Object.fromEntries(tracked.flatMap(key=>values[key]?.trim()?[[key,Number(values[key])]]:[]))});const updated=await getUser();if(updated)onSaved(updated);setMessage(en?"Body data and measurements saved.":"Kropp och mått sparade.")}catch(e){setMessage(e instanceof Error?e.message:en?"Could not save.":"Kunde inte spara.")}finally{setBusy(false)}}}>
    <h2 className="text-xl font-semibold">{labels.title}</h2><fieldset disabled={busy||!loaded} className="space-y-4"><BirthInputs value={body} onChange={setBody}/>
    <div className="grid gap-3 sm:grid-cols-2"><label>{labels.height}<input className="w-full border rounded p-2" type="number" min="100" max="250" step="any" value={height} onChange={e=>setHeight(e.target.value)}/></label><label>{labels.weight}<input className="w-full border rounded p-2" type="number" min="30" max="400" step="any" value={weight} onChange={e=>setWeight(e.target.value)}/></label></div>
    <p className="text-sm">{en?"Weight and height are needed for your personal plan. Birth year and sex for calculation are optional.":"Vikt och längd behövs för din personliga plan. Födelseår och kön för beräkning är frivilliga."}</p>
    <section id="measurements" className="mt-8 space-y-5 rounded-2xl border border-[#e6eadd] bg-[#fafcf8] p-5 sm:p-6 shadow-sm"><div className="space-y-1"><h3 className="text-lg font-semibold text-[#244d36]">{en?"Body measurements":"Kroppsmått"}</h3><p className="text-sm text-[#465c4c]">{en?"Measurements help track your progress over time. Values are saved to today's history.":"Mått hjälper dig följa dina framsteg över tid. Värden sparas i dagens historik."}</p></div>
      <div className="bg-white rounded-xl p-4 border border-[#e6eadd] shadow-sm"><label className="block font-medium text-[#244d36] mb-2">{en?"Waist (cm)":"Midja (cm)"}<input className="mt-1 w-full min-w-0 border border-[#d3dfd6] rounded-xl p-3 focus:ring-2 focus:ring-[#244d36]" type="number" min="30" max="250" step="any" value={waist} onChange={e=>setWaist(e.target.value)}/></label></div>
      <details className="group rounded-xl border border-[#e6eadd] bg-white overflow-hidden shadow-sm"><summary className="cursor-pointer bg-[#f7f9f5] px-4 py-3 text-sm font-medium text-[#244d36] transition-colors hover:bg-[#eaf2ec]">{en?"+ Manage other body measurements":"+ Hantera övriga kroppsmått"}</summary><div className="border-t border-[#e6eadd] p-4"><div className="grid grid-cols-2 gap-3 sm:grid-cols-3">{(Object.keys(measurementLabels) as MeasurementKey[]).map(key=><label key={key} className="flex min-h-[3rem] cursor-pointer items-center gap-2 rounded-lg border border-[#e6eadd] px-3 transition-colors hover:bg-[#f7f9f5] has-[:checked]:border-[#244d36] has-[:checked]:bg-[#f0f5eb]"><input type="checkbox" className="h-4 w-4 rounded border-[#d3dfd6] text-[#244d36] focus:ring-[#244d36]" checked={tracked.includes(key)} onChange={e=>setTracked(e.target.checked?[...tracked,key]:tracked.filter(value=>value!==key))}/><span className="text-sm font-medium">{names[key]}</span></label>)}</div></div></details>
      {tracked.length > 0 && <div className="grid gap-4 sm:grid-cols-2 md:grid-cols-3 pt-2">{(Object.keys(measurementLabels) as MeasurementKey[]).filter(key=>tracked.includes(key)).map(key=><div key={key} className="bg-white rounded-xl p-3 border border-[#e6eadd] shadow-sm"><label className="block text-sm font-medium text-[#244d36]">{names[key]} (cm)<input className="mt-1 w-full min-w-0 border border-[#d3dfd6] rounded-lg p-2.5 focus:ring-2 focus:ring-[#244d36]" type="number" min="1" max="250" step="any" value={values[key]??""} onChange={e=>setValues({...values,[key]:e.target.value})}/></label></div>)}</div>}
      <div className="flex items-center justify-between pt-2"><p className="text-sm text-[#617064]">{en?"Empty or hidden fields leave history unchanged.":"Tomma eller dolda fält ändrar inte tidigare historik."}</p><Link href="/progress" className="text-sm font-medium text-[#244d36] underline hover:text-[#1a3827]">{en?"View history in Progress":"Visa historik i Framsteg"}</Link></div>
    </section>
    <div className="pt-2"><Button disabled={busy||!loaded} className="w-full sm:w-auto h-12 px-8 text-base font-medium rounded-xl">{en?"Save body data and measurements":"Spara kropp och mått"}</Button></div></fieldset><p role="status">{message}</p>
  </form>
}
